
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsjyerikykwbitksdurq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zanllcmlreWt3Yml0a3NkdXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzQ0NjIsImV4cCI6MjA1NjUxMDQ2Mn0.Yh3DJlLkv8_PXa3Zrmva1A_YVC-oBFzrB6Y3IXvEVGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Event Interest functions
export const getEventInterestCount = async (eventId: string): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('event_interested')
      .select('*', { count: 'exact', head: true })
      .eq('event_id', eventId);
      
    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting event interest count:', error);
    return 0;
  }
};

export const isUserInterestedInEvent = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { data, error } = await supabase
      .from('event_interested')
      .select('*')
      .eq('event_id', eventId)
      .eq('user_id', userId)
      .maybeSingle();
      
    if (error) throw error;
    return !!data;
  } catch (error) {
    console.error('Error checking if user is interested in event:', error);
    return false;
  }
};

export const markEventInterest = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('event_interested')
      .insert({ event_id: eventId, user_id: userId });
      
    if (error) throw error;
    
    // Update the user's profile events_upcoming count
    // Fix: Properly handle the promise chain when updating profiles
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .select('events_upcoming')
      .eq('id', userId)
      .single();
      
    if (profileError) throw profileError;
    
    const currentCount = profileData?.events_upcoming || 0;
    const newCount = currentCount + 1;
    
    const { error: updateError } = await supabase
      .from('profiles')
      .update({ events_upcoming: newCount })
      .eq('id', userId);
    
    if (updateError) throw updateError;
    
    return true;
  } catch (error) {
    console.error('Error marking event interest:', error);
    return false;
  }
};

export const removeEventInterest = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('event_interested')
      .delete()
      .eq('event_id', eventId)
      .eq('user_id', userId);
      
    if (error) throw error;
    
    // Update the user's profile events_upcoming count
    // Fix: Properly handle the promise chain when updating profiles
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .select('events_upcoming')
      .eq('id', userId)
      .single();
      
    if (profileError) throw profileError;
    
    const currentCount = profileData?.events_upcoming || 0;
    const newCount = Math.max(0, currentCount - 1);
    
    const { error: updateError } = await supabase
      .from('profiles')
      .update({ events_upcoming: newCount })
      .eq('id', userId);
    
    if (updateError) throw updateError;
    
    return true;
  } catch (error) {
    console.error('Error removing event interest:', error);
    return false;
  }
};

// Event Attendees functions
export const getEventCheckedInCount = async (eventId: string): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('event_attendees_new')
      .select('*', { count: 'exact', head: true })
      .eq('event_id', eventId);
      
    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting event checked-in count:', error);
    return 0;
  }
};

export const getEventAttendees = async (eventId: string, includeProfiles = false): Promise<any[]> => {
  try {
    let query = supabase
      .from('event_attendees_new')
      .select(includeProfiles ? 'id, check_in_time, user_id, profiles:user_id(id, name, email)' : '*')
      .eq('event_id', eventId);
      
    const { data, error } = await query;
    
    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error getting event attendees:', error);
    return [];
  }
};

export const getEventInterestedUsers = async (eventId: string, includeProfiles = false): Promise<any[]> => {
  try {
    let query = supabase
      .from('event_interested')
      .select(includeProfiles ? 'id, created_at, user_id, profiles:user_id(id, name, email)' : '*')
      .eq('event_id', eventId);
      
    const { data, error } = await query;
    
    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error getting interested users:', error);
    return [];
  }
};

export const checkInUserToEvent = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    // Check if the user is already checked in
    const { data: existingCheckIn, error: checkError } = await supabase
      .from('event_attendees_new')
      .select('*')
      .eq('event_id', eventId)
      .eq('user_id', userId)
      .maybeSingle();
      
    if (checkError) throw checkError;
    
    // If user is already checked in, return success
    if (existingCheckIn) return true;
    
    // Otherwise, create a new check-in record
    const { error } = await supabase
      .from('event_attendees_new')
      .insert({ event_id: eventId, user_id: userId });
      
    if (error) throw error;
    
    // Fix: Properly handle the promise chain when updating profiles
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .select('events_attended')
      .eq('id', userId)
      .single();
      
    if (profileError) throw profileError;
    
    const currentCount = profileData?.events_attended || 0;
    const newCount = currentCount + 1;
    
    const { error: updateError } = await supabase
      .from('profiles')
      .update({ events_attended: newCount })
      .eq('id', userId);
      
    if (updateError) throw updateError;
    
    return true;
  } catch (error) {
    console.error('Error checking in user to event:', error);
    return false;
  }
};

// Admin functions
export const getTotalUsers = async (): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('profiles')
      .select('*', { count: 'exact', head: true });
      
    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting total users:', error);
    return 0;
  }
};

export const getTotalEvents = async (): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('events')
      .select('*', { count: 'exact', head: true });
      
    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting total events:', error);
    return 0;
  }
};

export const getInformationOfficers = async (): Promise<any[]> => {
  try {
    const { data, error } = await supabase
      .from('user_roles')
      .select('user_id, profiles:user_id(id, name, email)')
      .eq('role', 'information_officer');
      
    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error getting information officers:', error);
    return [];
  }
};

export const getStudents = async (): Promise<any[]> => {
  try {
    // Get users with only the student role (no other roles)
    const { data, error } = await supabase
      .from('user_roles')
      .select('user_id, profiles:user_id(id, name, email, events_attended)')
      .eq('role', 'student');
      
    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error getting students:', error);
    return [];
  }
};

export const demoteUserToStudent = async (userId: string): Promise<boolean> => {
  try {
    // First check if the user already has a student role
    const { data: existingStudentRole, error: checkError } = await supabase
      .from('user_roles')
      .select('*')
      .eq('user_id', userId)
      .eq('role', 'student')
      .maybeSingle();
      
    if (checkError) throw checkError;
    
    // Begin transaction
    // Remove information_officer role
    const { error: deleteError } = await supabase
      .from('user_roles')
      .delete()
      .eq('user_id', userId)
      .eq('role', 'information_officer');
      
    if (deleteError) throw deleteError;
    
    // If student role doesn't exist, add it
    if (!existingStudentRole) {
      const { error: insertError } = await supabase
        .from('user_roles')
        .insert({ user_id: userId, role: 'student' });
        
      if (insertError) throw insertError;
    }
    
    return true;
  } catch (error) {
    console.error('Error demoting user to student:', error);
    return false;
  }
};

export const promoteStudentToInfoOfficer = async (userId: string): Promise<boolean> => {
  try {
    // Add information_officer role
    const { error } = await supabase
      .from('user_roles')
      .insert({ user_id: userId, role: 'information_officer' });
      
    if (error) throw error;
    
    return true;
  } catch (error) {
    console.error('Error promoting student to information officer:', error);
    return false;
  }
};

export const getAllEvents = async (): Promise<any[]> => {
  try {
    const { data, error } = await supabase
      .from('events')
      .select('*')
      .order('event_date', { ascending: false });
      
    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error getting all events:', error);
    return [];
  }
};

export const deleteEvent = async (eventId: string): Promise<boolean> => {
  try {
    // Delete all related records first
    // 1. Delete event_interested records
    await supabase
      .from('event_interested')
      .delete()
      .eq('event_id', eventId);
      
    // 2. Delete event_attendees_new records
    await supabase
      .from('event_attendees_new')
      .delete()
      .eq('event_id', eventId);
      
    // 3. Delete the event itself
    const { error } = await supabase
      .from('events')
      .delete()
      .eq('id', eventId);
      
    if (error) throw error;
    
    return true;
  } catch (error) {
    console.error('Error deleting event:', error);
    return false;
  }
};

export const getUserAttendedEvents = async (userId: string): Promise<any[]> => {
  try {
    const { data, error } = await supabase
      .from('event_attendees_new')
      .select('event_id')
      .eq('user_id', userId);
      
    if (error) throw error;
    
    if (!data || data.length === 0) return [];
    
    // Get the event details for each attended event
    const eventIds = data.map(item => item.event_id);
    
    const { data: events, error: eventsError } = await supabase
      .from('events')
      .select('*')
      .in('id', eventIds)
      .order('event_date', { ascending: false });
      
    if (eventsError) throw eventsError;
    
    return events || [];
  } catch (error) {
    console.error('Error getting user attended events:', error);
    return [];
  }
};

// Event Reminder Notification functions
export const createEventReminderNotifications = async (): Promise<number> => {
  try {
    // Get the current time
    const now = new Date();
    
    // Get tomorrow's date at 11:59 PM
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(23, 59, 59, 999);
    
    // Get all active events happening within the next 24 hours that have not ended yet
    const { data: upcomingEvents, error: eventsError } = await supabase
      .from('events')
      .select('*')
      .gte('event_date', now.toISOString())
      .lte('event_date', tomorrow.toISOString())
      .eq('is_active', true);
      
    if (eventsError) throw eventsError;
    
    if (!upcomingEvents || upcomingEvents.length === 0) {
      console.log('No upcoming events in the next 24 hours');
      return 0;
    }
    
    console.log(`Found ${upcomingEvents.length} upcoming events in the next 24 hours`);
    
    let notificationsCreated = 0;
    
    // For each upcoming event
    for (const event of upcomingEvents) {
      // Get all users interested in this event
      const { data: interestedUsers, error: interestedError } = await supabase
        .from('event_interested')
        .select('user_id')
        .eq('event_id', event.id);
        
      if (interestedError) {
        console.error(`Error getting interested users for event ${event.id}:`, interestedError);
        continue;
      }
      
      if (!interestedUsers || interestedUsers.length === 0) {
        console.log(`No interested users for event ${event.id}`);
        continue;
      }
      
      console.log(`Found ${interestedUsers.length} interested users for event ${event.id}`);
      
      // Get event time in a readable format
      const eventDate = new Date(event.event_date);
      const formattedTime = eventDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      const formattedDate = eventDate.toLocaleDateString([], { month: 'short', day: 'numeric' });
      
      // Notify each interested user
      for (const user of interestedUsers) {
        // Check if user already has a reminder notification for this event
        const { data: existingNotification, error: checkError } = await supabase
          .from('notifications')
          .select('*')
          .eq('user_id', user.user_id)
          .eq('related_id', event.id.toString())
          .eq('type', 'reminder')
          .maybeSingle();
          
        if (checkError) {
          console.error(`Error checking existing notification for user ${user.user_id}:`, checkError);
          continue;
        }
        
        // Skip if user already has a reminder notification for this event
        if (existingNotification) {
          console.log(`User ${user.user_id} already has a reminder notification for event ${event.id}`);
          continue;
        }
        
        // Create notification
        const { error: notificationError } = await supabase
          .from('notifications')
          .insert({
            user_id: user.user_id,
            title: 'Event Reminder',
            message: `Your event "${event.title}" is happening soon at ${formattedTime} on ${formattedDate} ${event.location ? `at ${event.location}` : ''}`,
            type: 'reminder',
            related_id: event.id.toString(),
            read: false
          });
          
        if (notificationError) {
          console.error(`Error creating notification for user ${user.user_id}:`, notificationError);
          continue;
        }
        
        notificationsCreated++;
      }
      
      // Also notify information officers about the upcoming event
      const { data: infoOfficers, error: officersError } = await supabase
        .from('user_roles')
        .select('user_id')
        .eq('role', 'information_officer');
        
      if (officersError) {
        console.error('Error getting information officers:', officersError);
      } else if (infoOfficers && infoOfficers.length > 0) {
        console.log(`Found ${infoOfficers.length} information officers to notify about event ${event.id}`);
        
        for (const officer of infoOfficers) {
          // Skip if the officer is the event creator
          if (officer.user_id === event.created_by) {
            console.log(`Officer ${officer.user_id} is the event creator, skipping notification`);
            continue;
          }
          
          // Check if officer already has a reminder notification for this event
          const { data: existingNotification, error: checkError } = await supabase
            .from('notifications')
            .select('*')
            .eq('user_id', officer.user_id)
            .eq('related_id', event.id.toString())
            .eq('type', 'reminder')
            .maybeSingle();
            
          if (checkError) {
            console.error(`Error checking existing notification for officer ${officer.user_id}:`, checkError);
            continue;
          }
          
          // Skip if officer already has a reminder notification for this event
          if (existingNotification) {
            console.log(`Officer ${officer.user_id} already has a reminder notification for event ${event.id}`);
            continue;
          }
          
          // Create notification for information officer
          const { error: notificationError } = await supabase
            .from('notifications')
            .insert({
              user_id: officer.user_id,
              title: 'Event Status Update',
              message: `The event "${event.title}" you're overseeing is happening soon at ${formattedTime} on ${formattedDate} ${event.location ? `at ${event.location}` : ''}`,
              type: 'reminder',
              related_id: event.id.toString(),
              read: false
            });
            
          if (notificationError) {
            console.error(`Error creating notification for officer ${officer.user_id}:`, notificationError);
            continue;
          }
          
          notificationsCreated++;
        }
      }
    }
    
    return notificationsCreated;
  } catch (error) {
    console.error('Error creating event reminder notifications:', error);
    return 0;
  }
};
