// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsjyerikykwbitksdurq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zanllcmlreWt3Yml0a3NkdXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzQ0NjIsImV4cCI6MjA1NjUxMDQ2Mn0.Yh3DJlLkv8_PXa3Zrmva1A_YVC-oBFzrB6Y3IXvEVGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Get count of users interested in an event
export const getEventInterestCount = async (eventId: string): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('event_interested')
      .select('*', { count: 'exact', head: true })
      .eq('event_id', eventId);
      
    if (error) throw error;
    
    return count || 0;
  } catch (error) {
    console.error('Error getting event interest count:', error);
    return 0;
  }
};

// Get count of users checked in to an event
export const getEventCheckedInCount = async (eventId: string): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('event_attendees_new')
      .select('*', { count: 'exact', head: true })
      .eq('event_id', eventId);
      
    if (error) throw error;
    
    return count || 0;
  } catch (error) {
    console.error('Error getting event checked-in count:', error);
    return 0;
  }
};

// Check if a user is interested in an event
export const isUserInterestedInEvent = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { data, error } = await supabase
      .from('event_interested')
      .select('*')
      .eq('event_id', eventId)
      .eq('user_id', userId)
      .maybeSingle();
      
    if (error) throw error;
    
    return !!data;
  } catch (error) {
    console.error('Error checking if user is interested in event:', error);
    return false;
  }
};

// Mark user interest in an event
export const markEventInterest = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('event_interested')
      .insert({
        event_id: eventId,
        user_id: userId
      });
      
    if (error) throw error;
    
    return true;
  } catch (error) {
    console.error('Error marking event interest:', error);
    return false;
  }
};

// Remove user interest in an event
export const removeEventInterest = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('event_interested')
      .delete()
      .eq('event_id', eventId)
      .eq('user_id', userId);
      
    if (error) throw error;
    
    return true;
  } catch (error) {
    console.error('Error removing event interest:', error);
    return false;
  }
};

// Check in a user to an event
export const checkInUserToEvent = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    // Check if user is already checked in
    const { data: existingCheckIn, error: checkError } = await supabase
      .from('event_attendees_new')
      .select('*')
      .eq('event_id', eventId)
      .eq('user_id', userId)
      .maybeSingle();
      
    if (checkError) throw checkError;
    
    // If already checked in, return true
    if (existingCheckIn) {
      return true;
    }
    
    // Otherwise, create new check-in
    const { error } = await supabase
      .from('event_attendees_new')
      .insert({
        event_id: eventId,
        user_id: userId,
        check_in_time: new Date().toISOString()
      });
      
    if (error) throw error;
    
    // Increment events_attended counter in user profile
    try {
      // First get the current profile data
      const { data: currentProfile, error: profileError } = await supabase
        .from('profiles')
        .select('events_attended')
        .eq('id', userId)
        .single();
      
      if (profileError) {
        console.error('Error fetching profile for attendance update:', profileError);
        return true; // Still return true since check-in was successful
      }
      
      // Increment the events_attended count
      const { error: updateError } = await supabase
        .from('profiles')
        .update({ 
          events_attended: (currentProfile?.events_attended || 0) + 1 
        })
        .eq('id', userId);
      
      if (updateError) {
        console.error('Error updating profile attendance count:', updateError);
      }
    } catch (updateErr) {
      console.error('Error updating profile attendance count:', updateErr);
      // Don't throw here, as the check-in was successful
    }
    
    return true;
  } catch (error) {
    console.error('Error checking in user to event:', error);
    return false;
  }
};

// Get all attendees for an event with profile information
export const getEventAttendees = async (eventId: string, includeProfiles = false): Promise<any[]> => {
  try {
    let query = supabase
      .from('event_attendees_new')
      .select(includeProfiles ? 'id, user_id, check_in_time, profile:profiles(id, name, email)' : '*')
      .eq('event_id', eventId);
      
    const { data, error } = await query;
    
    if (error) throw error;
    
    return data || [];
  } catch (error) {
    console.error('Error getting event attendees:', error);
    return [];
  }
};

// Get all interested users for an event with profile information
export const getEventInterestedUsers = async (eventId: string, includeProfiles = false): Promise<any[]> => {
  try {
    let query = supabase
      .from('event_interested')
      .select(includeProfiles ? 'id, user_id, created_at, profile:profiles(id, name, email)' : '*')
      .eq('event_id', eventId);
      
    const { data, error } = await query;
    
    if (error) throw error;
    
    return data || [];
  } catch (error) {
    console.error('Error getting event interested users:', error);
    return [];
  }
};

// Get total number of users
export const getTotalUsers = async (): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('profiles')
      .select('*', { count: 'exact', head: true });
      
    if (error) throw error;
    
    return count || 0;
  } catch (error) {
    console.error('Error getting total users count:', error);
    return 0;
  }
};

// Get total number of events created
export const getTotalEvents = async (): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('events')
      .select('*', { count: 'exact', head: true });
      
    if (error) throw error;
    
    return count || 0;
  } catch (error) {
    console.error('Error getting total events count:', error);
    return 0;
  }
};

// Delete an event (Admin only)
export const deleteEvent = async (eventId: string): Promise<boolean> => {
  try {
    // Delete the event
    const { error } = await supabase
      .from('events')
      .delete()
      .eq('id', eventId);
      
    if (error) throw error;
    
    return true;
  } catch (error) {
    console.error('Error deleting event:', error);
    return false;
  }
};

// Demote a user from information_officer to student role (Admin only)
export const demoteUserToStudent = async (userId: string): Promise<boolean> => {
  try {
    // First check if the user has the information_officer role
    const { data: roles, error: rolesError } = await supabase
      .from('user_roles')
      .select('*')
      .eq('user_id', userId)
      .eq('role', 'information_officer');
      
    if (rolesError) throw rolesError;
    
    if (!roles || roles.length === 0) {
      console.warn('User does not have the information_officer role');
      return false;
    }
    
    // Delete the information_officer role
    const { error: deleteError } = await supabase
      .from('user_roles')
      .delete()
      .eq('user_id', userId)
      .eq('role', 'information_officer');
      
    if (deleteError) throw deleteError;
    
    // Ensure the user has the student role
    const { data: studentRoles, error: studentRolesError } = await supabase
      .from('user_roles')
      .select('*')
      .eq('user_id', userId)
      .eq('role', 'student');
      
    if (studentRolesError) throw studentRolesError;
    
    // If the user doesn't have the student role, add it
    if (!studentRoles || studentRoles.length === 0) {
      const { error: insertError } = await supabase
        .from('user_roles')
        .insert({
          user_id: userId,
          role: 'student'
        });
        
      if (insertError) throw insertError;
    }
    
    return true;
  } catch (error) {
    console.error('Error demoting user to student:', error);
    return false;
  }
};

// Get all users with information_officer role
export const getInformationOfficers = async (): Promise<any[]> => {
  try {
    const { data, error } = await supabase
      .from('user_roles')
      .select('user_id, profiles:profiles(id, name, email)')
      .eq('role', 'information_officer');
      
    if (error) throw error;
    
    return data || [];
  } catch (error) {
    console.error('Error getting information officers:', error);
    return [];
  }
};

// Get all events for admin management
export const getAllEvents = async (): Promise<any[]> => {
  try {
    const { data, error } = await supabase
      .from('events')
      .select('*')
      .order('created_at', { ascending: false });
      
    if (error) throw error;
    
    return data || [];
  } catch (error) {
    console.error('Error getting all events:', error);
    return [];
  }
};
