// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsjyerikykwbitksdurq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zanllcmlreWt3Yml0a3NkdXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzQ0NjIsImV4cCI6MjA1NjUxMDQ2Mn0.Yh3DJlLkv8_PXa3Zrmva1A_YVC-oBFzrB6Y3IXvEVGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Event Interest Functions
 */

// Get count of users interested in an event
export const getEventInterestCount = async (eventId: string): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('event_interested')
      .select('*', { count: 'exact', head: true })
      .eq('event_id', eventId);
      
    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting interest count:', error);
    return 0;
  }
};

// Check if a user is interested in an event
export const isUserInterestedInEvent = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { data, error } = await supabase
      .from('event_interested')
      .select('*')
      .eq('event_id', eventId)
      .eq('user_id', userId)
      .maybeSingle();
      
    if (error) throw error;
    return !!data;
  } catch (error) {
    console.error('Error checking user interest:', error);
    return false;
  }
};

// Mark a user as interested in an event
export const markEventInterest = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('event_interested')
      .insert({
        event_id: eventId,
        user_id: userId,
      });
      
    if (error) throw error;
    return true;
  } catch (error) {
    console.error('Error marking interest:', error);
    return false;
  }
};

// Remove a user's interest in an event
export const removeEventInterest = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('event_interested')
      .delete()
      .eq('event_id', eventId)
      .eq('user_id', userId);
      
    if (error) throw error;
    return true;
  } catch (error) {
    console.error('Error removing interest:', error);
    return false;
  }
};

/**
 * Event Attendance Functions
 */

// Check in a user to an event
export const checkInUserToEvent = async (eventId: string, userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('event_attendees_new')
      .insert({
        event_id: eventId,
        user_id: userId,
      });
      
    if (error) throw error;
    
    // Update user's attended events count - using a direct update
    // First get the count of events the user has attended
    const { count, error: countError } = await supabase
      .from('event_attendees_new')
      .select('*', { count: 'exact', head: true })
      .eq('user_id', userId);
    
    if (countError) {
      console.error('Error getting attended events count:', countError);
    } else {
      // Now update the profile with the count
      const { error: updateError } = await supabase
        .from('profiles')
        .update({ events_attended: count || 0 })
        .eq('id', userId);
      
      if (updateError) {
        console.error('Error updating attended events count:', updateError);
      }
    }
    
    return true;
  } catch (error) {
    console.error('Error checking in user:', error);
    return false;
  }
};

// Get count of users checked in to an event
export const getEventCheckedInCount = async (eventId: string): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('event_attendees_new')
      .select('*', { count: 'exact', head: true })
      .eq('event_id', eventId);
      
    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting check-in count:', error);
    return 0;
  }
};

// Get attendees of an event
export const getEventAttendees = async (eventId: string, includeProfiles = false): Promise<any[]> => {
  try {
    let query = supabase
      .from('event_attendees_new')
      .select(includeProfiles ? 'id, user_id, check_in_time, profiles:user_id(id, name, email)' : '*')
      .eq('event_id', eventId);
    
    const { data, error } = await query;
    
    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error getting event attendees:', error);
    return [];
  }
};

// Get users interested in an event
export const getEventInterestedUsers = async (eventId: string, includeProfiles = false): Promise<any[]> => {
  try {
    let query = supabase
      .from('event_interested')
      .select(includeProfiles ? 'id, user_id, created_at, profiles:user_id(id, name, email)' : '*')
      .eq('event_id', eventId);
    
    const { data, error } = await query;
    
    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error getting interested users:', error);
    return [];
  }
};

/**
 * Admin Functions
 */

// Get total number of users
export const getTotalUsers = async (): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('profiles')
      .select('*', { count: 'exact', head: true });
      
    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting total users:', error);
    return 0;
  }
};

// Get total number of events
export const getTotalEvents = async (): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from('events')
      .select('*', { count: 'exact', head: true });
      
    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error('Error getting total events:', error);
    return 0;
  }
};

// Get all information officers
export const getInformationOfficers = async (): Promise<any[]> => {
  try {
    console.log('Fetching information officers...');
    
    // First, fetch all user_ids with the information_officer role
    const { data: roleData, error: roleError } = await supabase
      .from('user_roles')
      .select('user_id')
      .eq('role', 'information_officer');
    
    if (roleError) {
      console.error("Error fetching officer roles:", roleError);
      return [];
    }
    
    console.log("Role data:", roleData);
    
    if (!roleData || roleData.length === 0) {
      console.log("No information officers found");
      return [];
    }
    
    // Extract user_ids from the role data
    const officerIds = roleData.map(item => item.user_id);
    console.log("Found officer IDs:", officerIds);
    
    // Then, fetch the profile data for those user_ids
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .select('id, name, email')
      .in('id', officerIds);
    
    if (profileError) {
      console.error("Error fetching profiles:", profileError);
      return [];
    }
    
    console.log("Retrieved profiles:", profileData);
    
    // Format the data to include both user_id and profile info
    const officers = profileData.map(profile => ({
      user_id: profile.id,
      profiles: profile
    }));
    
    return officers || [];
  } catch (error) {
    console.error('Error getting information officers:', error);
    return [];
  }
};

// Demote an information officer to student
export const demoteUserToStudent = async (userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('user_roles')
      .update({ role: 'student' })
      .eq('user_id', userId)
      .eq('role', 'information_officer');
      
    if (error) throw error;
    return true;
  } catch (error) {
    console.error('Error demoting user:', error);
    return false;
  }
};

// Get all events
export const getAllEvents = async (): Promise<any[]> => {
  try {
    const { data, error } = await supabase
      .from('events')
      .select('*')
      .order('event_date', { ascending: false });
      
    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error getting all events:', error);
    return [];
  }
};

// Delete an event
export const deleteEvent = async (eventId: string): Promise<boolean> => {
  try {
    // First delete related data
    const deleteInterestedPromise = supabase
      .from('event_interested')
      .delete()
      .eq('event_id', eventId);
      
    const deleteAttendeesPromise = supabase
      .from('event_attendees_new')
      .delete()
      .eq('event_id', eventId);
    
    await Promise.all([deleteInterestedPromise, deleteAttendeesPromise]);
    
    // Now delete the event
    const { error } = await supabase
      .from('events')
      .delete()
      .eq('id', eventId);
      
    if (error) throw error;
    return true;
  } catch (error) {
    console.error('Error deleting event:', error);
    return false;
  }
};

/**
 * Student Management Functions
 */

// Get all students
export const getStudents = async (): Promise<any[]> => {
  try {
    console.log('Fetching students...');
    
    // First, fetch all user_ids with the student role
    const { data: roleData, error: roleError } = await supabase
      .from('user_roles')
      .select('user_id')
      .eq('role', 'student');
    
    if (roleError) {
      console.error("Error fetching student roles:", roleError);
      return [];
    }
    
    console.log("Role data:", roleData);
    
    if (!roleData || roleData.length === 0) {
      console.log("No students found");
      return [];
    }
    
    // Extract user_ids from the role data
    const studentIds = roleData.map(item => item.user_id);
    console.log("Found student IDs:", studentIds);
    
    // Then, fetch the profile data for those user_ids
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .select('id, name, email, events_attended')
      .in('id', studentIds);
    
    if (profileError) {
      console.error("Error fetching profiles:", profileError);
      return [];
    }
    
    console.log("Retrieved profiles:", profileData);
    
    // Format the data to include both user_id and profile info
    const students = profileData.map(profile => ({
      user_id: profile.id,
      profiles: profile
    }));
    
    return students || [];
  } catch (error) {
    console.error('Error getting students:', error);
    return [];
  }
};

// Promote a student to information officer
export const promoteStudentToInfoOfficer = async (userId: string): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('user_roles')
      .update({ role: 'information_officer' })
      .eq('user_id', userId)
      .eq('role', 'student');
      
    if (error) throw error;
    return true;
  } catch (error) {
    console.error('Error promoting student:', error);
    return false;
  }
};

/**
 * User Events Functions
 */

// Get events attended by a user
export const getUserAttendedEvents = async (userId: string): Promise<any[]> => {
  try {
    // First get the event IDs the user has attended
    const { data: attendanceData, error: attendanceError } = await supabase
      .from('event_attendees_new')
      .select('event_id')
      .eq('user_id', userId);
      
    if (attendanceError) {
      console.error('Error getting user attendance:', attendanceError);
      return [];
    }
    
    if (!attendanceData || attendanceData.length === 0) {
      return [];
    }
    
    // Extract the event IDs
    const eventIds = attendanceData.map(item => item.event_id);
    
    // Now fetch the event details
    const { data: eventsData, error: eventsError } = await supabase
      .from('events')
      .select('id, title, event_date, location, image_url')
      .in('id', eventIds)
      .order('event_date', { ascending: false });
      
    if (eventsError) {
      console.error('Error getting events:', eventsError);
      return [];
    }
    
    return eventsData || [];
  } catch (error) {
    console.error('Error getting user attended events:', error);
    return [];
  }
};
